"""IPSec configuration generator — regenerates ipsec.conf from the database."""

from __future__ import annotations

from datetime import datetime, timezone

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.db.models import Tunnel
from app.logging_config import get_logger
from app.services import s3, ssm
from app.services.locks import LOCK_IPSEC_CONFIG, require_lock

logger = get_logger(__name__)

_IPSEC_CONF_HEADER = """\
# ipsec.conf — AUTO-GENERATED by strongswan-manager
# Generated at: {timestamp}
# DO NOT EDIT MANUALLY — changes will be overwritten.

config setup
    charondebug="ike 2, knl 2, cfg 2"

"""

_TUNNEL_BLOCK_TEMPLATE = """\
conn {name}
    keyexchange=ikev{ike_version}
    left=%defaultroute
    leftsubnet={local_cidrs}
    right={peer_ip}
    rightsubnet={remote_cidrs}
    authby=secret
    auto=start
    ikelifetime=8h
    lifetime=1h
    dpdaction={dpd_action}
    dpddelay={dpd_delay}s
    dpdtimeout={dpd_timeout}s
"""


def _render_tunnel_block(tunnel: Tunnel) -> str:
    """Render a single ``conn`` block for an IPSec tunnel."""
    return _TUNNEL_BLOCK_TEMPLATE.format(
        name=tunnel.name,
        ike_version=tunnel.ike_version,
        local_cidrs=",".join(tunnel.local_cidrs),
        peer_ip=tunnel.peer_ip,
        remote_cidrs=",".join(tunnel.remote_cidrs),
        dpd_action=tunnel.dpd_action,
        dpd_delay=tunnel.dpd_delay,
        dpd_timeout=tunnel.dpd_timeout,
    )


async def generate_ipsec_conf(session: AsyncSession) -> str:
    """Generate the complete ipsec.conf from all active tunnels in the database.

    The database is the source of truth. Every call queries ALL active
    tunnels and renders the full configuration from scratch — no
    read-modify-write.

    Args:
        session: Active database session.

    Returns:
        The rendered ipsec.conf content as a string.
    """
    result = await session.execute(
        select(Tunnel).where(
            Tunnel.deleted_at.is_(None),
            Tunnel.status == "active",
        ).order_by(Tunnel.name),
    )
    tunnels = result.scalars().all()

    timestamp = datetime.now(timezone.utc).isoformat()
    header = _IPSEC_CONF_HEADER.format(timestamp=timestamp)

    if not tunnels:
        logger.info("ipsec_config_generated", tunnel_count=0)
        return header

    blocks = [_render_tunnel_block(t) for t in tunnels]
    content = header + "\n".join(blocks)

    logger.info("ipsec_config_generated", tunnel_count=len(tunnels))
    return content


async def sync_ipsec_config(session: AsyncSession) -> None:
    """Regenerate ipsec.conf, upload to S3, and reload IPSec on VPN instances.

    This is the single entry-point called by tunnel orchestration services
    after any tunnel CRUD operation. The caller MUST have already acquired
    ``LOCK_IPSEC_CONFIG`` via :func:`require_lock` — this function does
    NOT acquire the lock itself so the lock remains held for the entire
    transaction.

    Args:
        session: Active database session.

    Raises:
        InfrastructureError: If S3 upload or SSM reload fails.
    """
    logger.info("ipsec_sync_start")

    content = await generate_ipsec_conf(session)
    await s3.upload_ipsec_conf(content)
    await ssm.reload_ipsec()

    logger.info("ipsec_sync_complete")
